DemoDashboardDevice/Controllers/DeviceController.cs
using DemoDashboardDevice.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DemoDashboardDevice.Controllers
{
    public class DeviceController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public List<Device> GetListDevice()
        {
            List<Device> devices = Tools.GetListDevice(new List<Device>());
            return devices;
        }
    }
}

DemoDashboardDevice/Controllers/EmployeeController.cs
using DemoDashboardDevice.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DemoDashboardDevice.Controllers
{
    public class EmployeeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public List<Person> GetListEmployee()
        {
            List<Person> employees = Tools.GetListEmployee(new List<Person>());
            return employees;
        }
    }
}

DemoDashboardDevice/Views/Shared/_Footer.cshtml
  <!-- Main Footer -->
<footer class="main-footer">
    <!-- To the right -->
    <div class="float-right d-none d-sm-inline">
        DEMO
    </div>
    <!-- Default to the left -->
    <!--<strong>Copyright &copy; 2014-2019 <a href="https://adminlte.io">AdminLTE.io</a>.</strong> All rights reserved.-->
</footer>

DemoDashboardDevice/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Demo</title>
    @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />*@
    @*<link rel="stylesheet" href="~/css/site.css" />*@
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="~/adminlte/plugins/fontawesome-free/css/all.min.css">

    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

    <link rel="stylesheet" href="~/adminlte/plugins/fontawesome-free/css/all.min.css">
    <link href="~/adminlte/bootstrap-5.1.0-dist/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/adminlte/plugins/daterangepicker/daterangepicker.css" rel="stylesheet" />

    <!-- DataTables -->
    <link rel="stylesheet" href="~/adminlte/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="~/adminlte/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
    <link rel="stylesheet" href="~/adminlte/plugins/datatables-buttons/css/buttons.bootstrap4.min.css">
    <link href="~/adminlte/plugins/select2/css/select2.min.css" rel="stylesheet" />
    <link href="~/adminlte/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css" rel="stylesheet" />
    <link href="~/adminlte/bootstrap-5.1.0-dist/select2/css/select2-bootstrap-5-theme.min.css" rel="stylesheet" />
    <link href="~/adminlte/plugins/datatables-select/css/select.bootstrap4.min.css" rel="stylesheet" />
    <link href="~/adminlte/plugins/datatables-fixedcolumns/css/fixedColumns.bootstrap4.min.css" rel="stylesheet" />
    <link href="~/adminlte/plugins/datatables-rowgroup/css/rowGroup.bootstrap4.min.css" rel="stylesheet" />
    <!-- sweetalert2 -->
    <link href="~/adminlte/plugins/sweetalert2-theme-bootstrap-4/bootstrap-4.min.css" rel="stylesheet" />
    <!-- Theme style -->
    <link rel="stylesheet" href="~/adminlte/dist/css/adminlte.min.css">
    <style>
        .loadmio {
            display: none;
            position: fixed;
            z-index: 1000;
            top: 0;
            left: 0;
            height: 100%;
            width: 100%;
            background: rgba( 255, 255, 255, .8 ) url('/img/ajax-loader7.gif') 50% 50% no-repeat;
        }

        /* When the body has the loading class, we turn
           the scrollbar off with overflow:hidden */

        body.loading {
            overflow: hidden;
        }

            /* Anytime the body has the loading class, our
           modal element will be visible */

            body.loading .loadmio {
                display: block;
            }
    </style>
    @RenderSection("Styles", required: false)
</head>
<body class="sidebar-mini control-sidebar-push">


    <div class="wrapper">
        <div class="modal loadmio"></div>
        <partial name="_Navbar" />
        <partial name="_Sidebar" />
        <partial name="_SidebarControl" />
        <div class="content-wrapper">
            <div class="content">
                <div class="container-fluid">

                    @RenderBody()

                </div>
            </div>

        </div>

        @*<partial name="_Footer" />*@
    </div>

    <!-- jQuery -->
    <script src="~/adminlte/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 5 -->
    <script src="~/adminlte/bootstrap-5.1.0-dist/js/bootstrap.bundle.js"></script>
    <!-- ChartJS -->
    <script src="~/adminlte/plugins/chart.js/Chart.min.js"></script>
    <!-- daterangepicker -->
    <script src="~/adminlte/plugins/moment/moment-with-locales.js"></script>
    <script src="~/adminlte/plugins/daterangepicker/daterangepicker.js"></script>
    <!-- DataTables  & Plugins -->
    <script src="~/adminlte/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="~/adminlte/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
    <script src="~/adminlte/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
    <script src="~/adminlte/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
    <script src="~/adminlte/plugins/datatables-buttons/js/dataTables.buttons.min.js"></script>
    <script src="~/adminlte/plugins/datatables-buttons/js/buttons.bootstrap4.min.js"></script>
    <script src="~/adminlte/plugins/jszip/jszip.min.js"></script>
    <script src="~/adminlte/plugins/pdfmake/pdfmake.min.js"></script>
    <script src="~/adminlte/plugins/pdfmake/vfs_fonts.js"></script>
    <script src="~/adminlte/plugins/datatables-buttons/js/buttons.html5.min.js"></script>
    <script src="~/adminlte/plugins/datatables-buttons/js/buttons.print.min.js"></script>
    <script src="~/adminlte/plugins/datatables-buttons/js/buttons.colVis.min.js"></script>
    <script src="~/adminlte/plugins/select2/js/select2.min.js"></script>
    <script src="~/adminlte/plugins/datatables-select/js/dataTables.select.min.js"></script>
    <script src="~/adminlte/plugins/datatables-select/js/select.bootstrap4.min.js"></script>
    <script src="~/adminlte/plugins/datatables-fixedcolumns/js/dataTables.fixedColumnsLast.min.js"></script>

    <script src="~/adminlte/plugins/datatables-rowgroup/js/dataTables.rowGroup.min.js"></script>


    <!-- sweetalert2 -->
    <script src="~/adminlte/plugins/sweetalert2/sweetalert2.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/adminlte/dist/js/adminlte.min.js"></script>

    <script src="~/jsViews/AjaxLoading.js"></script>

    <script type="text/javascript">
        
    </script>
    @RenderSection("Scripts", required: false)
</body>
</html>

DemoDashboardDevice/Views/Shared/_Navbar.cshtml
  <!-- Navbar -->
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>

    </ul>

    <!-- SEARCH FORM -->
    <form class="form-inline ml-3">
    </form>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
    </ul>


</nav>
<!-- /.navbar -->

DemoDashboardDevice/Views/Shared/_Sidebar.cshtml
 <!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-primary elevation-4">
  <!-- Brand Logo -->
  <a href="#" class="brand-link">
    <img src="~/adminlte/dist/img/Logo_original2.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
         style="opacity: .8">
    <span class="brand-text font-weight-light">DEMO</span>
  </a>

  <!-- Sidebar -->
  <div class="sidebar">
    <!-- Sidebar user panel (optional) -->
    <div class="user-panel mt-3 pb-3 mb-3 d-flex">
      
        <div class="info">
            <span id="username" class="badge badge-primary">User</span>
        </div>
    </div>

    <!-- Sidebar Menu -->
    <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
            <!-- Add icons to the links using the .nav-icon class
    with font-awesome or any other icon font library -->
            <li id="ColaboradorView" class="nav-item has-treeview menu-open">
                <a href="#" class="nav-link active">
                    <i class="nav-icon fas fa-user"></i>
                    <p>
                        ADMIN
                        <i class="right fas fa-angle-left"></i>
                    </p>
                </a>
                <ul class="nav nav-treeview">
                    <li id="ColList" class="nav-item">
                        <a href="@Url.Action("Index", "Employee")" class="nav-link">
                            <i class="fa fa-indent nav-icon"></i>
                            <p>Colaboradores</p>
                        </a>
                    </li>
                    <li id="DeviceList" class="nav-item">

                        <a href="@Url.Action("Index", "Device")" class="nav-link">
                            <i class="fa fa-exchange-alt nav-icon"></i>
                            <p>Dispositivos</p>
                        </a>
                    </li>
                    

                </ul>
            </li>
        </ul>
    </nav>
    <!-- /.sidebar-menu -->
  </div>
  <!-- /.sidebar -->
</aside>

DemoDashboardDevice/Views/Shared/_SidebarControl.cshtml
 <!-- Control Sidebar Container -->
<aside class="control-sidebar control-sidebar-light">
    <!-- Control sidebar content goes here -->
    <ul class="nav nav-tabs" role="tablist">
        <li class="nav-item">
            <a class="nav-link aside-menu-toggler" data-widget="control-sidebar">
                <i class="fas fa-times"></i>
            </a>
        </li>
    </ul>
    <div class="superdiv control-sidebar-content">
        <!-- Content of the sidebar goes here -->
    </div>
    <ul class="nav nav-tabs" role="tablist">
        <li class="nav-item">
            <a class="nav-link aside-menu-toggler" data-widget="control-sidebar">
                <i class="fas fa-times"></i>
            </a>
        </li>
    </ul>
</aside>

DemoDashboardDevice/Views/Shared/_menurot.cshtml
<div id="menu_rot">
    
</div>